# https://github.com/Mic92/sops-nix
keys:
  - &admin_kyle age18f7tep34xrlp3mart5rq8ch04qz668xcusryfjhq54e05xj623sscsyy6l
  - &server_jupiter age1t5ss2r43mcalddv0p4ddy6lp2kf95enagsrf8u6jlfsw056wf5zqmr73wd
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin_kyle
      - *server_jupiter
